---
- name: Make sure the latest package versions are installed
  apt:
    update-cache: yes

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Install containerd on the machines
  apt:
    name: containerd
    state: present
  register: containerd

- name: Create the containerd folder on the machines
  file:
    path: /etc/containerd
    state: directory
    mode: 0755
  when: containerd.changed != false

- name: Install containerd default config
  shell: containerd config default  /etc/containerd/config.toml
  when: containerd.changed != false

- name: Install KubeADM dependencies and key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kuberenetes repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Install kubernetes executables
  apt:
    pkg:
      - kubeadm
      - kubelet
      - kubectl
  register: kubernetes_executables

- name: Configuring ip tables
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.bridge.bridge-nf-call-iptables"
    line: net.bridge.bridge-nf-call-iptables = 1
  when: kubernetes_executables.changed != false

- name: Configuring ip fowarding
  become: yes
  shell: echo '1' > /proc/sys/net/ipv4/ip_forward
  when: kubernetes_executables.changed != false

- name: Configure kernel
  shell: sysctl --system
  when: kubernetes_executables.changed != false

- name: Configure modprob
  shell: |
    modprobe overlay
    modprobe br_netfilter
    swapoff -a
  when: kubernetes_executables.changed != false
