---
- name: Join instances to kubefedctl
  hosts: master
  become: yes

  tasks:
    - name: Join self
      ignore_errors: yes
      command: kubefedctl join master --v=2 --host-cluster-context master --kubefed-namespace=kube-federation-system

    - name: Join slave
      ignore_errors: yes
      command: "kubefedctl join {{region|lower}} --v=2 --host-cluster-context master --kubefed-namespace=kube-federation-system "

    - name: Display the clusters to verify
      command: kubectl -n kube-federation-system get kubefedclusters
      register: clusters

    - name: Debug the clusters
      debug:
        msg: "{{clusters.stdout_lines}}"

- name: Enable federation services
  hosts: master
  become: yes

  tasks:
    - name: Enable deployments for kubefed
      command: kubefedctl enable deployments.apps --kubefed-namespace kube-federation-system

    - name: Enable services for kubefed
      command: kubefedctl enable services --kubefed-namespace kube-federation-system
