##On the slave##
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: <REPLACE_ME>
  name: <REPLACE_ME>
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: <REPLACE_ME>
  name: <REPLACE_ME>
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: <REPLACE_ME>
  name: <REPLACE_ME>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: <REPLACE_ME>
subjects:
  - kind: ServiceAccount
    name: <REPLACE_ME>
    namespace: default
