---
- name: Load token as variable
  become: no
  local_action: command cat ./rbac-token
  register: token

- name: Add the credentials to the master
  command: "kubectl config set-credentials {{region|lower}}-user --token={{token.stdout}}"

- name: Add the Master remote ip
  command: "kubectl config set-cluster {{region|lower}} --server=https://{{groups[region][0]}}:6443"

- name: Set the context
  command: "kubectl config set-context {{region|lower}} --cluster={{region|lower}} --user={{region|lower}}-user --namespace='default' "

- name: Copy the certificate to the master
  copy:
    src: ./rbac-certificate
    dest: "/tmp/rbac-certificate-{{region|lower}}.crt"
    mode: 0400
  register: certificate

- name: Insert certificate into file
  lineinfile:
    path: $HOME/.kube/config
    line: "    certificate-authority: /tmp/rbac-certificate-{{region|lower}}.crt"
    insertbefore: "    server: https://{{groups[region][0]}}:6443\n"
  when: certificate.changed != false

- name: Rename kubernetes-admin to master
  lineinfile:
    path: $HOME/.kube/config
    regexp: "^  name: kubernetes-admin@kubernetes$"
    line: "  name: master"
  when: certificate.changed != false

- name: Rename current context to master
  lineinfile:
    path: $HOME/.kube/config
    regexp: "^current-context: kubernetes-admin@kubernetes$"
    line: "current-context: master"
  when: certificate.changed != false
